apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
data:
  node.properties: |
    node.environment=production
    node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
    node.data-dir=/data/trino

  jvm.config: |
    -server
    -Xmx2G
    -XX:+UseG1GC
    -XX:+UseStringDeduplication

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.https.enabled=false
    http-server.http.port=8080
    query.max-memory=1.5GB
    query.max-memory-per-node=1GB
    discovery.uri=http://trino-service:8080

  mongodb.properties: |
    connector.name=mongodb
    mongodb.connection-url=mongodb://root:root@mongo-service:27017/?authSource=admin

  # clickhouse.properties: |
  #   connector.name=clickhouse
  #   connection-url=jdbc:clickhouse://clickhouse-service:8123/
  #   connection-user=it4931
  #   connection-password=it4931
