apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-connect
  template:
    metadata:
      labels:
        app: k-connect
    spec:
      containers:
        - name: k-connect
          image: confluentinc/cp-kafka-connect:7.5.10
          ports:
            - containerPort: 8083
          command:
            - bash
            - -c
            - |
              # Install HDFS3 connector
              confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs3:2.0.3

              # Start Kafka Connect
              /etc/confluent/docker/run
          env:
            # Required Configuration
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "k-broker-0.k-broker-svc:9094,k-broker-1.k-broker-svc:9094"
            - name: CONNECT_GROUP_ID
              value: "it4931"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "_k-connect-config"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "_k-connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "_k-connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "k-connect-svc"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components,/connectors"
            # Replication Factors
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            # HDFS Configuration
            - name: HADOOP_CONF_DIR
              value: "/etc/hadoop"
          volumeMounts:
            - name: connectors
              mountPath: /connectors
            - name: hadoop-config
              mountPath: /etc/hadoop
          resources:
            requests:
              cpu: "250m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "4Gi"
      volumes:
        - name: connectors
          emptyDir: {}
        - name: hadoop-config
          configMap:
            name: hdfs-config

# check connector class: curl http://$(minikube ip):30838/connector-plugins
# deploy connector instance: curl -X POST http://$(minikube ip):30838/connectors \ -H "Content-Type: application/json" -d file_path 