version: "3.8"
name: ingestion-kafka

networks:
  ingestion-net:
    name: ingestion-net

volumes:
  broker01-data:
  broker02-data:
  spark-events:
  spark-checkpoints:
  connect-plugins:

services:
  broker01:
    image: confluentinc/cp-kafka:8.1.0
    container_name: broker01
    hostname: broker01
    networks: [ingestion-net]
    ports:
      - "19092:19092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker01:9093,2@broker02:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "INTERNAL://broker01:9092,CONTROLLER://broker01:9093,EXTERNAL://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker01:9092,EXTERNAL://localhost:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - broker01-data:/var/lib/kafka/data
    restart: unless-stopped


  broker02:
    image: confluentinc/cp-kafka:8.1.0
    container_name: broker02
    hostname: broker02
    networks: [ingestion-net]
    ports:
      - "29092:29092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker01:9093,2@broker02:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "INTERNAL://broker02:9092,CONTROLLER://broker02:9093,EXTERNAL://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker02:9092,EXTERNAL://localhost:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - broker02-data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks: [ingestion-net]
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-kraft"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker01:9092,broker02:9092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker01
      - broker02
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    container_name: schema-registry
    hostname: schema-registry
    networks: [ingestion-net]
    depends_on:
      - broker01
      - broker02
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker01:9092,broker02:9092"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    ports:
      - "8081:8081"
    restart: unless-stopped

  kafka-connect:
    build: ./kafka-connect
    image: kafka-connect-hdfs3:latest
    container_name: kafka-connect
    hostname: kafka-connect
    networks: [ingestion-net]
    depends_on:
      - broker01
      - broker02
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "broker01:9092,broker02:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_GROUP_ID: "connect-cluster"

      CONNECT_CONFIG_STORAGE_TOPIC: "__connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "__connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "__connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

      CONNECT_CONFLUENT_TOPIC_BOOTSTRAP_SERVERS: "broker01:9092,broker02:9092"
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 2

      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

    volumes:
      - connect-plugins:/usr/share/confluent-hub-components
    restart: unless-stopped
