apiVersion: v1
kind: Service
metadata:
  name: dagster-webserver
spec:
  selector:
    app: dagster
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: dagster-postgresql-svc
spec:
  selector:
    app: dagster-postgresql
  ports:
    - port: 5432